"""drop path columns

Revision ID: 4320cb091f28
Revises: 0fff4c4f7863
Create Date: 2021-02-27 14:49:07.976133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4320cb091f28'
down_revision = '0fff4c4f7863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_column('html_path')
        batch_op.drop_column('pdf_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_path', sa.VARCHAR(length=250), nullable=True))
        batch_op.add_column(sa.Column('html_path', sa.VARCHAR(length=250), nullable=True))

    # ### end Alembic commands ###
