"""adding back community district since I realize now that's community BOARD district

Revision ID: df3fd30ef0fb
Revises: e2b2ad518f47
Create Date: 2021-03-06 12:35:31.238277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df3fd30ef0fb'
down_revision = 'e2b2ad518f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_district', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_school_community_district'), ['community_district'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_community_district'))
        batch_op.drop_column('community_district')

    # ### end Alembic commands ###
